/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class runGA */

#ifndef _Included_runGA
#define _Included_runGA
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     runGA
 * Method:    runGA
 * Signature: ([I[IIIDD[D[I[I[I[I)I
 */
JNIEXPORT jint JNICALL Java_runGA_runGA
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jdouble, jdouble, jdoubleArray, jintArray, jintArray, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
